### ISSUE TITLE
FileNotFoundError: 'hist/acc/MNIST-iid_FedAvg_FL_5_600_5_200_0.001.pkl

### ISSUE THREAD

**Issue by qiaojy19** [Accenture/Labs-Federated-Learning#1]
Hi, I just git clone the code and run `sh simple_experiment.sh`.
then the program reports the file not found error.
Could you help me?
Thank you very much.

**Comment by YannFra** [comment]
Hi qiaojy19, 
Thanks for bringing up this issue.I have corrected it and running `sh simple_experiment.sh` should work. Please let me know if you still have an issue running this code.
